spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update


springdoc:
  swagger-ui:
    path: /api/delivery-point-rating/data-service/swagger-ui.html