name: pull request

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:1
      - name: Save Docker image  
        run: docker save --output image.tar my-image-name:1
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar
          retention-days: 1
